# Generated by Django 5.2.2 on 2025-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(default="Engineering", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(default="2+", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(default="Remote", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("part-time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                ],
                max_length=50,
            ),
        ),
    ]
