# Generated by Django 5.2.2 on 2025-06-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_benefits_job_category_job_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="benefits",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="job",
            name="responsibilities",
            field=models.JSONField(default=list),
        ),
    ]
