# Generated by Django 5.2.2 on 2025-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_benefits_alter_job_requirements_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responsibility", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="job",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="job",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="job",
            name="responsibilities",
        ),
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.ManyToManyField(to="jobs.jobbenefit"),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.ManyToManyField(to="jobs.jobrequirement"),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.ManyToManyField(to="jobs.jobresponsibility"),
        ),
    ]
