# Generated by Django 5.2.2 on 2025-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobbenefit_jobrequirement_jobresponsibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
