# Generated by Django 5.2.2 on 2025-07-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobapplication_cover_letter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-posted_at"]},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="posted_date",
            new_name="posted_at",
        ),
    ]
