# Generated by Django 5.2.2 on 2025-07-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_options_rename_posted_date_job_posted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.IntegerField()),
                ("max", models.IntegerField()),
                ("currency", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="jobs.salary",
            ),
        ),
    ]
