# Generated by Django 5.2.2 on 2025-07-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_salary_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
    ]
