# Generated by Django 5.2.2 on 2025-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobapplication_linkedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("interview", "Interview Scheduled"),
                    ("offer", "Job Offer Extended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
