# Generated by Django 5.2.2 on 2025-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_project_created_at_project_deadline_alter_project_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed_percentage",
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
