# Generated by Django 5.2.2 on 2025-07-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_completed_percentage_project_is_featured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="picture",
            new_name="image",
        ),
    ]
