# Generated by Django 5.2.2 on 2025-07-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_rename_picture_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="projects.technology"
            ),
        ),
    ]
