# Generated by Django 5.2.2 on 2025-07-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_technology_project_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="check_out_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
