# Generated by Django 5.2.2 on 2025-07-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_check_out_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="descriptions",
            new_name="description",
        ),
    ]
