# Generated by Django 5.2.2 on 2025-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="picture",
            new_name="avatar",
        ),
        migrations.RemoveField(
            model_name="testimonal",
            name="client",
        ),
        migrations.AddField(
            model_name="testimonal",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="testimonal",
            name="name",
            field=models.CharField(default="John Doe", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimonal",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
