# Generated by Django 5.2.2 on 2025-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_rename_picture_client_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("features", models.ManyToManyField(to="clients.servicefeature")),
            ],
        ),
    ]
