# Generated by Django 5.2.2 on 2025-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_servicefeature_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
