# Generated by Django 5.2.2 on 2025-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_mission_message_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("number_of_employees", models.PositiveBigIntegerField(default=10)),
                (
                    "number_of_projects_completed",
                    models.PositiveBigIntegerField(default=10),
                ),
                (
                    "client_satisfication_rate",
                    models.PositiveBigIntegerField(default=10),
                ),
                ("number_of_happy_clients", models.PositiveBigIntegerField(default=10)),
                (
                    "number_of_years_in_business",
                    models.PositiveBigIntegerField(default=5),
                ),
                ("company_location", models.CharField(max_length=255)),
            ],
        ),
    ]
