# Generated by Django 5.2.2 on 2025-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_companystats"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="company_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="company_name",
            field=models.CharField(default="Gumisofts", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(default="contact@gumisofts.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_phone",
            field=models.CharField(default="+251953541616", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="number_of_happy_clients",
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="number_of_projects_completed",
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="number_of_years_in_business",
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
