# Generated by Django 5.2.2 on 2025-07-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_company_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="company_location",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="contact_phone",
        ),
    ]
