# Generated by Django 5.2.2 on 2025-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_twitter_url_organization_telegram_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="client_satisfication_rate",
            field=models.PositiveBigIntegerField(default=98),
        ),
    ]
