# Generated by Django 5.2.2 on 2025-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_organization_client_satisfication_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="number_of_employees",
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
