# Generated by Django 5.2.2 on 2025-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_organization_number_of_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="number_of_services",
            field=models.PositiveBigIntegerField(default=6),
        ),
    ]
