# Generated by Django 5.2.2 on 2025-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_category_tag_blogpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="unsubscribe_token",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
